-- Dummy/test seed data for FTL Dashboard testing (requested for a testing22 walkthrough):
-- 60 master vendor-rate lanes, 5 sales submissions (20 lanes each, mixed vehicle types),
-- with some rows already resolved to a rate and some with no matching master lane, and a
-- mix of VM requests (open/in_progress/resolved) covering both "seeking a lower rate" and
-- "missing lane" cases. Safe to delete this data manually later; it's not re-run (Flyway
-- migrations are one-shot).
-- Master vendor rates:
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Bekasi', 'Kota Yogyakarta', 'CDE', 'kab. bekasi', 'kota yogyakarta', 'cde', NULL, 15765000.0, 14543000.0, 15578000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Bekasi', 'Kota Yogyakarta', 'CDD-L', 'kab. bekasi', 'kota yogyakarta', 'cdd-l', 6464000.0, 6493000.0, 6373000.0, 6488000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Bekasi', 'Kota Surabaya', 'Wingbox', 'kab. bekasi', 'kota surabaya', 'wingbox', 8012000.0, 7570000.0, 7690000.0, 8371000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Bekasi', 'Kota Surabaya', 'CDD', 'kab. bekasi', 'kota surabaya', 'cdd', 14671000.0, NULL, 14480000.0, 16780000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Bekasi', 'Kab. Sidoarjo', 'CDD-L', 'kab. bekasi', 'kab. sidoarjo', 'cdd-l', 5943000.0, 6278000.0, 5878000.0, 6453000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Bekasi', 'Kab. Sidoarjo', 'Wingbox', 'kab. bekasi', 'kab. sidoarjo', 'wingbox', 13204000.0, 14314000.0, 13498000.0, 14680000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Bekasi', 'Kota Makassar', 'CDD', 'kab. bekasi', 'kota makassar', 'cdd', 11282000.0, 11141000.0, 10790000.0, 11092000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Bekasi', 'Kota Makassar', 'CDE', 'kab. bekasi', 'kota makassar', 'cde', 3504000.0, 3795000.0, 3507000.0, 3751000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Bekasi', 'Kota Lampung', 'Wingbox', 'kab. bekasi', 'kota lampung', 'wingbox', 7626000.0, 7857000.0, 7281000.0, 8283000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Bekasi', 'Kota Lampung', 'CDE', 'kab. bekasi', 'kota lampung', 'cde', 5103000.0, 5267000.0, 5312000.0, 5394000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Bekasi', 'Kota Semarang', 'Wingbox', 'kab. bekasi', 'kota semarang', 'wingbox', 11364000.0, NULL, 10759000.0, 11546000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Bekasi', 'Kota Semarang', 'CDD-L', 'kab. bekasi', 'kota semarang', 'cdd-l', 7357000.0, 7438000.0, 7413000.0, 8299000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Timur', 'Kota Medan', 'CDD-L', 'kota jakarta timur', 'kota medan', 'cdd-l', NULL, NULL, NULL, 12758000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Timur', 'Kota Medan', 'CDE', 'kota jakarta timur', 'kota medan', 'cde', NULL, NULL, 4639000.0, 5365000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Timur', 'Kota Lampung', 'CDE', 'kota jakarta timur', 'kota lampung', 'cde', 14621000.0, 16156000.0, 14784000.0, 15816000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Timur', 'Kota Lampung', 'Wingbox', 'kota jakarta timur', 'kota lampung', 'wingbox', 18456000.0, NULL, 17433000.0, 18506000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Timur', 'Kota Yogyakarta', 'CDD-L', 'kota jakarta timur', 'kota yogyakarta', 'cdd-l', 11389000.0, 11458000.0, 11433000.0, 12642000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Timur', 'Kota Yogyakarta', 'CDD', 'kota jakarta timur', 'kota yogyakarta', 'cdd', 4149000.0, NULL, 3767000.0, 4106000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Timur', 'Kota Solo', 'CDD', 'kota jakarta timur', 'kota solo', 'cdd', 17755000.0, 18902000.0, 16574000.0, 18728000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Timur', 'Kota Solo', 'CDD-L', 'kota jakarta timur', 'kota solo', 'cdd-l', NULL, 11332000.0, 10049000.0, 11831000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Timur', 'Kota Palembang', 'CDE', 'kota jakarta timur', 'kota palembang', 'cde', 6182000.0, 6259000.0, 6283000.0, 6825000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Timur', 'Kota Palembang', 'Wingbox', 'kota jakarta timur', 'kota palembang', 'wingbox', 12419000.0, 11989000.0, 12167000.0, 12846000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Timur', 'Kota Semarang', 'Wingbox', 'kota jakarta timur', 'kota semarang', 'wingbox', 16734000.0, 18907000.0, 17464000.0, 18414000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Timur', 'Kota Semarang', 'CDE', 'kota jakarta timur', 'kota semarang', 'cde', NULL, 16057000.0, 14497000.0, NULL);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Utara', 'Kota Balikpapan', 'Wingbox', 'kota jakarta utara', 'kota balikpapan', 'wingbox', 16539000.0, 18452000.0, 16062000.0, NULL);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Utara', 'Kota Balikpapan', 'CDD-L', 'kota jakarta utara', 'kota balikpapan', 'cdd-l', 10156000.0, 10163000.0, 9404000.0, 10384000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Utara', 'Kab. Garut', 'CDD-L', 'kota jakarta utara', 'kab. garut', 'cdd-l', 13864000.0, 14915000.0, 13555000.0, 14445000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Utara', 'Kab. Garut', 'CDE', 'kota jakarta utara', 'kab. garut', 'cde', 10756000.0, 11051000.0, 9987000.0, 10842000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Utara', 'Kab. Malang', 'CDD', 'kota jakarta utara', 'kab. malang', 'cdd', 8041000.0, 8104000.0, NULL, 7842000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Utara', 'Kab. Malang', 'Wingbox', 'kota jakarta utara', 'kab. malang', 'wingbox', 17430000.0, 17861000.0, 16839000.0, 17101000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Utara', 'Kab. Kediri', 'CDD-L', 'kota jakarta utara', 'kab. kediri', 'cdd-l', 6340000.0, 6571000.0, 6595000.0, 6643000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Utara', 'Kab. Kediri', 'Wingbox', 'kota jakarta utara', 'kab. kediri', 'wingbox', 9646000.0, 10025000.0, NULL, 10650000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Utara', 'Kota Manado', 'Wingbox', 'kota jakarta utara', 'kota manado', 'wingbox', 3303000.0, 3143000.0, 3027000.0, 3328000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Utara', 'Kota Manado', 'CDD-L', 'kota jakarta utara', 'kota manado', 'cdd-l', 3849000.0, 3950000.0, NULL, 3826000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Utara', 'Kota Surabaya', 'CDE', 'kota jakarta utara', 'kota surabaya', 'cde', 16691000.0, NULL, 16270000.0, 16478000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Jakarta Utara', 'Kota Surabaya', 'CDD', 'kota jakarta utara', 'kota surabaya', 'cdd', 17046000.0, 17313000.0, 16613000.0, 18039000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Tangerang', 'Kota Makassar', 'CDE', 'kab. tangerang', 'kota makassar', 'cde', 7014000.0, 7156000.0, NULL, 7250000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Tangerang', 'Kota Makassar', 'CDD', 'kab. tangerang', 'kota makassar', 'cdd', 10038000.0, NULL, 9528000.0, 10760000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Tangerang', 'Kab. Sidoarjo', 'CDD-L', 'kab. tangerang', 'kab. sidoarjo', 'cdd-l', NULL, 5124000.0, NULL, 5282000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Tangerang', 'Kab. Sidoarjo', 'CDE', 'kab. tangerang', 'kab. sidoarjo', 'cde', 8636000.0, 9074000.0, 8601000.0, 9522000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Tangerang', 'Kota Medan', 'CDE', 'kab. tangerang', 'kota medan', 'cde', 16894000.0, 17317000.0, 15346000.0, 17225000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Tangerang', 'Kota Medan', 'CDD-L', 'kab. tangerang', 'kota medan', 'cdd-l', 7956000.0, NULL, 8152000.0, 8935000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Tangerang', 'Kota Yogyakarta', 'CDD', 'kab. tangerang', 'kota yogyakarta', 'cdd', 9932000.0, 10018000.0, 9661000.0, 10448000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Tangerang', 'Kota Yogyakarta', 'CDE', 'kab. tangerang', 'kota yogyakarta', 'cde', 6578000.0, 6699000.0, 6149000.0, 7195000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Tangerang', 'Kab. Banyuwangi', 'CDD', 'kab. tangerang', 'kab. banyuwangi', 'cdd', 4495000.0, 4370000.0, NULL, 4599000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Tangerang', 'Kab. Banyuwangi', 'CDD-L', 'kab. tangerang', 'kab. banyuwangi', 'cdd-l', 15746000.0, 16985000.0, 15351000.0, 17751000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Tangerang', 'Kota Pekanbaru', 'CDD', 'kab. tangerang', 'kota pekanbaru', 'cdd', 14536000.0, 15407000.0, NULL, NULL);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kab. Tangerang', 'Kota Pekanbaru', 'CDD-L', 'kab. tangerang', 'kota pekanbaru', 'cdd-l', 17722000.0, 19234000.0, 16541000.0, 19586000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Bandung', 'Kota Jambi', 'Wingbox', 'kota bandung', 'kota jambi', 'wingbox', 16682000.0, 17256000.0, NULL, 17629000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Bandung', 'Kota Jambi', 'CDD-L', 'kota bandung', 'kota jambi', 'cdd-l', 7598000.0, 7779000.0, 6942000.0, 7956000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Bandung', 'Kota Denpasar', 'CDD', 'kota bandung', 'kota denpasar', 'cdd', 8669000.0, 8655000.0, 8548000.0, 9068000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Bandung', 'Kota Denpasar', 'Wingbox', 'kota bandung', 'kota denpasar', 'wingbox', 11574000.0, 12329000.0, 12264000.0, 13318000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Bandung', 'Kota Manado', 'Wingbox', 'kota bandung', 'kota manado', 'wingbox', NULL, 3157000.0, NULL, 3297000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Bandung', 'Kota Manado', 'CDD', 'kota bandung', 'kota manado', 'cdd', 15483000.0, 15342000.0, 14165000.0, 16536000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Bandung', 'Kota Lampung', 'Wingbox', 'kota bandung', 'kota lampung', 'wingbox', 6011000.0, NULL, 5824000.0, 6215000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Bandung', 'Kota Lampung', 'CDD-L', 'kota bandung', 'kota lampung', 'cdd-l', 4248000.0, 4336000.0, 4153000.0, 4795000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Bandung', 'Kab. Kediri', 'Wingbox', 'kota bandung', 'kab. kediri', 'wingbox', NULL, 16624000.0, 15525000.0, 17302000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Bandung', 'Kab. Kediri', 'CDD', 'kota bandung', 'kab. kediri', 'cdd', 6952000.0, 7142000.0, NULL, 6824000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Bandung', 'Kab. Banyuwangi', 'CDD', 'kota bandung', 'kab. banyuwangi', 'cdd', 4920000.0, NULL, 4843000.0, 5482000.0);
INSERT INTO vendor_rates (origin, destination, vehicle_type, norm_origin, norm_destination, norm_vehicle_type, duta_cost, seryu_cost, ab_cargo_cost, sjl_cost) VALUES ('Kota Bandung', 'Kab. Banyuwangi', 'CDE', 'kota bandung', 'kab. banyuwangi', 'cde', 15980000.0, 15712000.0, 15729000.0, 17153000.0);
INSERT INTO master_rate_uploads (uploaded_by, filename, row_count) VALUES ('vm.dummy@ninjavan.co', 'dummy_seed.csv', 60);
-- Sales submissions + rows + VM requests:
INSERT INTO submissions (uploaded_by, filename, shipper_name, sales_pic, shipper_status, potential_monthly_revenue, commodity_type, high_value_fragile, add_ons) VALUES ('workinpns@gmail.com', 'dummy_batch_1.csv', 'PT Sinar Abadi Logistik', 'Rina Wulandari', 'new', 45000000, 'Consumer Goods', 0, NULL);
SET @sid_0 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kota Jakarta Utara', 'Kota Balikpapan', 'Wingbox', 19254000.0, 19374600.0, 'Already bottom rate', 'Seryu', 18452000.0);
SET @rid_0_0 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_0_0, 'Kota Jakarta Utara', 'Kota Balikpapan', 'Wingbox', 19254000.0, 19374600.0, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kota Bandung', 'Kota Manado', 'CDD', 14686000.0, 14873250.0, 'Already bottom rate', 'AB Cargo', 14165000.0);
SET @rid_0_1 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_0_1, 'Kota Bandung', 'Kota Manado', 'CDD', 14686000.0, 14873250.0, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kab. Bekasi', 'Kota Pekanbaru (Baru)', 'CDD-L', NULL, NULL, 'No rate available', NULL, NULL);
SET @rid_0_2 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_0_2, 'Kab. Bekasi', 'Kota Pekanbaru (Baru)', 'CDD-L', NULL, NULL, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kab. Tangerang', 'Kota Yogyakarta', 'CDE', NULL, 7308158.0, '', 'Duta Trans', 6578000.0);
SET @rid_0_3 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kab. Tangerang', 'Kota Medan', 'CDE', 18926000.0, 18182850.0, 'Already bottom rate', 'Seryu', 17317000.0);
SET @rid_0_4 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_0_4, 'Kab. Tangerang', 'Kota Medan', 'CDE', 18926000.0, 18182850.0, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kab. Bekasi', 'Kota Pekanbaru (Baru)', 'Wingbox', 12235000, NULL, 'No rate available', NULL, NULL);
SET @rid_0_5 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_0_5, 'Kab. Bekasi', 'Kota Pekanbaru (Baru)', 'Wingbox', 12235000, NULL, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kab. Tangerang', 'Kab. Banyuwangi', 'CDD-L', 16030000.0, 16533300.0, 'Already bottom rate', 'Duta Trans', 15746000.0);
SET @rid_0_6 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_0_6, 'Kab. Tangerang', 'Kab. Banyuwangi', 'CDD-L', 16030000.0, 16533300.0, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kota Jakarta Utara', 'Kota Balikpapan', 'CDD-L', NULL, 11283316.0, '', 'Duta Trans', 10156000.0);
SET @rid_0_7 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kota Jakarta Timur', 'Kota Medan', 'CDD-L', NULL, 14174138.0, '', 'SJL', 12758000.0);
SET @rid_0_8 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kab. Tangerang', 'Kota Denpasar (Baru)', 'Wingbox', NULL, NULL, 'No rate available', NULL, NULL);
SET @rid_0_9 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_0_9, 'Kab. Tangerang', 'Kota Denpasar (Baru)', 'Wingbox', NULL, NULL, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kab. Bekasi', 'Kab. Sidoarjo', 'CDD-L', 7030000.0, 6775650.0, 'Already bottom rate', 'SJL', 6453000.0);
SET @rid_0_10 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_0_10, 'Kab. Bekasi', 'Kab. Sidoarjo', 'CDD-L', 7030000.0, 6775650.0, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kab. Bekasi', 'Kota Makassar', 'CDD', NULL, 12323212.0, '', 'SJL', 11092000.0);
SET @rid_0_11 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kota Jakarta Timur', 'Kota Solo', 'CDD-L', NULL, 12589852.0, '', 'Seryu', 11332000.0);
SET @rid_0_12 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kab. Tangerang', 'Kab. Sidoarjo', 'CDD-L', NULL, 5868302.0, '', 'SJL', 5282000.0);
SET @rid_0_13 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kab. Tangerang', 'Kab. Banyuwangi', 'CDD', NULL, 4993945.0, '', 'Duta Trans', 4495000.0);
SET @rid_0_14 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kab. Bekasi', 'Kota Balikpapan (Baru)', 'CDE', NULL, NULL, 'No rate available', NULL, NULL);
SET @rid_0_15 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_0_15, 'Kab. Bekasi', 'Kota Balikpapan (Baru)', 'CDE', NULL, NULL, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kota Jakarta Utara', 'Kab. Garut (Baru)', 'Wingbox', NULL, NULL, 'No rate available', NULL, NULL);
SET @rid_0_16 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_0_16, 'Kota Jakarta Utara', 'Kab. Garut (Baru)', 'Wingbox', NULL, NULL, 'workinpns@gmail.com', 'resolved', 'Seryu', 7970000);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kota Jakarta Timur', 'Kota Lampung', 'Wingbox', 17796000.0, 18304650.0, 'Already bottom rate', 'AB Cargo', 17433000.0);
SET @rid_0_17 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_0_17, 'Kota Jakarta Timur', 'Kota Lampung', 'Wingbox', 17796000.0, 18304650.0, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kota Jakarta Utara', 'Kota Semarang (Baru)', 'CDD-L', 4915000, NULL, 'No rate available', NULL, NULL);
SET @rid_0_18 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_0_18, 'Kota Jakarta Utara', 'Kota Semarang (Baru)', 'CDD-L', 4915000, NULL, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_0, 'Kab. Tangerang', 'Kota Makassar', 'CDD', NULL, 11152218.0, '', 'Duta Trans', 10038000.0);
SET @rid_0_19 = LAST_INSERT_ID();
INSERT INTO submissions (uploaded_by, filename, shipper_name, sales_pic, shipper_status, potential_monthly_revenue, commodity_type, high_value_fragile, add_ons) VALUES ('workinpns@gmail.com', 'dummy_batch_2.csv', 'PT Nusantara Cipta Mandiri', 'Bayu Pratama', 'existing', 120000000, 'Electronics', 1, NULL);
SET @sid_1 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kota Jakarta Timur', 'Kota Palembang', 'Wingbox', 12283000.0, 12775350.0, 'Already bottom rate', 'AB Cargo', 12167000.0);
SET @rid_1_0 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_1_0, 'Kota Jakarta Timur', 'Kota Palembang', 'Wingbox', 12283000.0, 12775350.0, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kota Jakarta Utara', 'Kab. Kediri', 'CDD-L', 7568000.0, 7380373.0, 'Meets target', 'SJL', 6643000.0);
SET @rid_1_1 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kab. Bekasi', 'Kota Makassar', 'CDD', NULL, 12323212.0, '', 'SJL', 11092000.0);
SET @rid_1_2 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kota Jakarta Utara', 'Kab. Kediri', 'Wingbox', 12430000.0, 11832150.0, 'Meets target', 'SJL', 10650000.0);
SET @rid_1_3 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kab. Bekasi', 'Kota Yogyakarta', 'CDE', NULL, 17307158.0, '', 'SJL', 15578000.0);
SET @rid_1_4 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kota Jakarta Timur', 'Kota Solo', 'CDD', NULL, 19725805.0, '', 'Duta Trans', 17755000.0);
SET @rid_1_5 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kab. Bekasi', 'Kota Makassar (Baru)', 'CDE', NULL, NULL, 'No rate available', NULL, NULL);
SET @rid_1_6 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_1_6, 'Kab. Bekasi', 'Kota Makassar (Baru)', 'CDE', NULL, NULL, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kota Bandung', 'Kota Jambi', 'Wingbox', NULL, 19171416.0, '', 'Seryu', 17256000.0);
SET @rid_1_7 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kota Bandung', 'Kota Lampung', 'CDD-L', 4313000.0, 4552800.0, 'Already bottom rate', 'Seryu', 4336000.0);
SET @rid_1_8 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_1_8, 'Kota Bandung', 'Kota Lampung', 'CDD-L', 4313000.0, 4552800.0, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kota Jakarta Utara', 'Kab. Malang', 'CDD', NULL, 8933551.0, '', 'Duta Trans', 8041000.0);
SET @rid_1_9 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kota Bandung', 'Kota Pekanbaru (Baru)', 'CDD', 9102000, NULL, 'No rate available', NULL, NULL);
SET @rid_1_10 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_1_10, 'Kota Bandung', 'Kota Pekanbaru (Baru)', 'CDD', 9102000, NULL, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kota Bandung', 'Kab. Banyuwangi', 'CDE', NULL, 17474919.0, '', 'AB Cargo', 15729000.0);
SET @rid_1_11 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kab. Tangerang', 'Kota Makassar', 'CDE', 7171000.0, 7513800.0, 'Already bottom rate', 'Seryu', 7156000.0);
SET @rid_1_12 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_1_12, 'Kab. Tangerang', 'Kota Makassar', 'CDE', 7171000.0, 7513800.0, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kab. Bekasi', 'Kab. Banyuwangi (Baru)', 'Wingbox', 8200000, NULL, 'No rate available', NULL, NULL);
SET @rid_1_13 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_1_13, 'Kab. Bekasi', 'Kab. Banyuwangi (Baru)', 'Wingbox', 8200000, NULL, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kab. Bekasi', 'Kota Surabaya', 'CDD', 18521000.0, 17619000.0, 'Already bottom rate', 'SJL', 16780000.0);
SET @rid_1_14 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_1_14, 'Kab. Bekasi', 'Kota Surabaya', 'CDD', 18521000.0, 17619000.0, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kota Bandung', 'Kota Denpasar', 'Wingbox', 14736000.0, 13983900.0, 'Already bottom rate', 'SJL', 13318000.0);
SET @rid_1_15 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_1_15, 'Kota Bandung', 'Kota Denpasar', 'Wingbox', 14736000.0, 13983900.0, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kota Jakarta Timur', 'Kota Denpasar (Baru)', 'CDD-L', NULL, NULL, 'No rate available', NULL, NULL);
SET @rid_1_16 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_1_16, 'Kota Jakarta Timur', 'Kota Denpasar (Baru)', 'CDD-L', NULL, NULL, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kota Jakarta Utara', 'Kab. Purwokerto (Baru)', 'CDE', NULL, NULL, 'No rate available', NULL, NULL);
SET @rid_1_17 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_1_17, 'Kota Jakarta Utara', 'Kab. Purwokerto (Baru)', 'CDE', NULL, NULL, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kab. Bekasi', 'Kota Semarang', 'CDD-L', 8942000.0, 8713950.0, 'Already bottom rate', 'SJL', 8299000.0);
SET @rid_1_18 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_1_18, 'Kab. Bekasi', 'Kota Semarang', 'CDD-L', 8942000.0, 8713950.0, 'workinpns@gmail.com', 'resolved', 'Duta Trans', 7334000.0);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_1, 'Kab. Bekasi', 'Kota Balikpapan (Baru)', 'CDE', 10851000, NULL, 'No rate available', NULL, NULL);
SET @rid_1_19 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_1_19, 'Kab. Bekasi', 'Kota Balikpapan (Baru)', 'CDE', 10851000, NULL, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submissions (uploaded_by, filename, shipper_name, sales_pic, shipper_status, potential_monthly_revenue, commodity_type, high_value_fragile, add_ons) VALUES ('workinpns@gmail.com', 'dummy_batch_3.csv', 'PT Cahaya Distribusi Utama', 'Dewi Anggraini', 'new', 30000000, 'F&B', 0, NULL);
SET @sid_2 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kab. Bekasi', 'Kota Surabaya', 'Wingbox', NULL, 8543590.0, '', 'AB Cargo', 7690000.0);
SET @rid_2_0 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kab. Bekasi', 'Kota Palembang (Baru)', 'CDD-L', 5971000, NULL, 'No rate available', NULL, NULL);
SET @rid_2_1 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_2_1, 'Kab. Bekasi', 'Kota Palembang (Baru)', 'CDD-L', 5971000, NULL, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kota Jakarta Utara', 'Kab. Garut', 'CDD-L', 16182000.0, 15660750.0, 'Already bottom rate', 'Seryu', 14915000.0);
SET @rid_2_2 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_2_2, 'Kota Jakarta Utara', 'Kab. Garut', 'CDD-L', 16182000.0, 15660750.0, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kota Bandung', 'Kota Jambi (Baru)', 'Wingbox', 12095000, NULL, 'No rate available', NULL, NULL);
SET @rid_2_3 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_2_3, 'Kota Bandung', 'Kota Jambi (Baru)', 'Wingbox', 12095000, NULL, 'workinpns@gmail.com', 'resolved', 'Seryu', 10664000);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kota Jakarta Utara', 'Kota Balikpapan', 'CDD-L', NULL, 11283316.0, '', 'Duta Trans', 10156000.0);
SET @rid_2_4 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kab. Tangerang', 'Kota Lampung (Baru)', 'CDE', NULL, NULL, 'No rate available', NULL, NULL);
SET @rid_2_5 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_2_5, 'Kab. Tangerang', 'Kota Lampung (Baru)', 'CDE', NULL, NULL, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kota Jakarta Utara', 'Kota Surabaya', 'CDD', NULL, 18938106.0, '', 'Duta Trans', 17046000.0);
SET @rid_2_6 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kota Bandung', 'Kota Lampung', 'Wingbox', 7060000.0, 6904865.0, 'Meets target', 'SJL', 6215000.0);
SET @rid_2_7 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kab. Bekasi', 'Kota Semarang', 'Wingbox', NULL, 12625404.0, '', 'Duta Trans', 11364000.0);
SET @rid_2_8 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kota Jakarta Utara', 'Kab. Kediri (Baru)', 'CDE', 9009000, NULL, 'No rate available', NULL, NULL);
SET @rid_2_9 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_2_9, 'Kota Jakarta Utara', 'Kab. Kediri (Baru)', 'CDE', 9009000, NULL, 'workinpns@gmail.com', 'resolved', 'SJL', 5493000);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kab. Tangerang', 'Kota Yogyakarta', 'CDD', 11592000.0, 10970400.0, 'Already bottom rate', 'SJL', 10448000.0);
SET @rid_2_10 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_2_10, 'Kab. Tangerang', 'Kota Yogyakarta', 'CDD', 11592000.0, 10970400.0, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kota Bandung', 'Kab. Purwokerto (Baru)', 'Wingbox', 9399000, NULL, 'No rate available', NULL, NULL);
SET @rid_2_11 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_2_11, 'Kota Bandung', 'Kab. Purwokerto (Baru)', 'Wingbox', 9399000, NULL, 'workinpns@gmail.com', 'resolved', 'Seryu', 12593000);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kab. Tangerang', 'Kota Semarang (Baru)', 'CDD-L', 10892000, NULL, 'No rate available', NULL, NULL);
SET @rid_2_12 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_2_12, 'Kab. Tangerang', 'Kota Semarang (Baru)', 'CDD-L', 10892000, NULL, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kota Bandung', 'Kota Jambi', 'Wingbox', NULL, 19171416.0, '', 'Seryu', 17256000.0);
SET @rid_2_13 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kota Jakarta Utara', 'Kab. Kediri', 'Wingbox', NULL, 11137775.0, '', 'Seryu', 10025000.0);
SET @rid_2_14 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kota Bandung', 'Kab. Banyuwangi', 'CDE', NULL, 17474919.0, '', 'AB Cargo', 15729000.0);
SET @rid_2_15 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kota Jakarta Timur', 'Kota Palembang', 'Wingbox', NULL, 13517537.0, '', 'AB Cargo', 12167000.0);
SET @rid_2_16 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kota Jakarta Timur', 'Kota Solo', 'CDD', 20527000.0, 19847100.0, 'Already bottom rate', 'Seryu', 18902000.0);
SET @rid_2_17 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_2_17, 'Kota Jakarta Timur', 'Kota Solo', 'CDD', 20527000.0, 19847100.0, 'workinpns@gmail.com', 'resolved', 'AB Cargo', 16365000.0);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kab. Tangerang', 'Kab. Banyuwangi', 'CDD', 5325000.0, 5109489.0, 'Meets target', 'SJL', 4599000.0);
SET @rid_2_18 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_2, 'Kab. Bekasi', 'Kota Makassar', 'CDD', 12658000.0, 12534302.0, 'Meets target', 'Duta Trans', 11282000.0);
SET @rid_2_19 = LAST_INSERT_ID();
INSERT INTO submissions (uploaded_by, filename, shipper_name, sales_pic, shipper_status, potential_monthly_revenue, commodity_type, high_value_fragile, add_ons) VALUES ('workinpns@gmail.com', 'dummy_batch_4.csv', 'PT Global Trans Sejahtera', 'Fajar Ramadhan', 'existing', 78000000, 'Automotive Parts', 0, NULL);
SET @sid_3 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kota Bandung', 'Kab. Banyuwangi', 'CDD', 5903000.0, 5756100.0, 'Already bottom rate', 'SJL', 5482000.0);
SET @rid_3_0 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_3_0, 'Kota Bandung', 'Kab. Banyuwangi', 'CDD', 5903000.0, 5756100.0, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kota Jakarta Utara', 'Kota Makassar (Baru)', 'CDE', NULL, NULL, 'No rate available', NULL, NULL);
SET @rid_3_1 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_3_1, 'Kota Jakarta Utara', 'Kota Makassar (Baru)', 'CDE', NULL, NULL, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kab. Tangerang', 'Kota Medan', 'CDD-L', 9238000.0, 9381750.0, 'Already bottom rate', 'SJL', 8935000.0);
SET @rid_3_2 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_3_2, 'Kab. Tangerang', 'Kota Medan', 'CDD-L', 9238000.0, 9381750.0, 'workinpns@gmail.com', 'resolved', 'Duta Trans', 7946000.0);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kab. Bekasi', 'Kab. Malang (Baru)', 'CDD-L', 11119000, NULL, 'No rate available', NULL, NULL);
SET @rid_3_3 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_3_3, 'Kab. Bekasi', 'Kab. Malang (Baru)', 'CDD-L', 11119000, NULL, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kota Bandung', 'Kota Semarang (Baru)', 'CDD', 9069000, NULL, 'No rate available', NULL, NULL);
SET @rid_3_4 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_3_4, 'Kota Bandung', 'Kota Semarang (Baru)', 'CDD', 9069000, NULL, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kota Jakarta Utara', 'Kota Balikpapan', 'CDD-L', 11149000.0, 10903200.0, 'Already bottom rate', 'SJL', 10384000.0);
SET @rid_3_5 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_3_5, 'Kota Jakarta Utara', 'Kota Balikpapan', 'CDD-L', 11149000.0, 10903200.0, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kota Jakarta Timur', 'Kota Yogyakarta', 'CDD-L', NULL, 12702063.0, '', 'AB Cargo', 11433000.0);
SET @rid_3_6 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kab. Tangerang', 'Kota Medan', 'CDE', 19163000.0, 18182850.0, 'Already bottom rate', 'Seryu', 17317000.0);
SET @rid_3_7 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_3_7, 'Kab. Tangerang', 'Kota Medan', 'CDE', 19163000.0, 18182850.0, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kota Jakarta Utara', 'Kota Balikpapan', 'Wingbox', NULL, 18374829.0, '', 'Duta Trans', 16539000.0);
SET @rid_3_8 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kab. Tangerang', 'Kab. Garut (Baru)', 'CDE', NULL, NULL, 'No rate available', NULL, NULL);
SET @rid_3_9 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_3_9, 'Kab. Tangerang', 'Kab. Garut (Baru)', 'CDE', NULL, NULL, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kab. Tangerang', 'Kota Medan (Baru)', 'CDD-L', NULL, NULL, 'No rate available', NULL, NULL);
SET @rid_3_10 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_3_10, 'Kab. Tangerang', 'Kota Medan (Baru)', 'CDD-L', NULL, NULL, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kab. Bekasi', 'Kab. Sidoarjo', 'Wingbox', NULL, 14996278.0, '', 'AB Cargo', 13498000.0);
SET @rid_3_11 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kab. Tangerang', 'Kota Yogyakarta', 'CDE', NULL, 7308158.0, '', 'Duta Trans', 6578000.0);
SET @rid_3_12 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kab. Tangerang', 'Kab. Banyuwangi', 'CDD', 5432000.0, 5109489.0, 'Meets target', 'SJL', 4599000.0);
SET @rid_3_13 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kab. Tangerang', 'Kab. Sidoarjo', 'CDE', NULL, 9594596.0, '', 'Duta Trans', 8636000.0);
SET @rid_3_14 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kab. Tangerang', 'Kab. Banyuwangi', 'CDD-L', NULL, 17493806.0, '', 'Duta Trans', 15746000.0);
SET @rid_3_15 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kab. Tangerang', 'Kota Yogyakarta (Baru)', 'CDE', NULL, NULL, 'No rate available', NULL, NULL);
SET @rid_3_16 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_3_16, 'Kab. Tangerang', 'Kota Yogyakarta (Baru)', 'CDE', NULL, NULL, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kota Jakarta Timur', 'Kota Palembang', 'CDE', 7647000.0, 7582575.0, 'Meets target', 'SJL', 6825000.0);
SET @rid_3_17 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kota Jakarta Utara', 'Kota Surabaya', 'CDE', 17325000.0, 17525550.0, 'Already bottom rate', 'Duta Trans', 16691000.0);
SET @rid_3_18 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_3_18, 'Kota Jakarta Utara', 'Kota Surabaya', 'CDE', 17325000.0, 17525550.0, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_3, 'Kota Jakarta Timur', 'Kota Palembang', 'Wingbox', 15534000.0, 14271906.0, 'Meets target', 'SJL', 12846000.0);
SET @rid_3_19 = LAST_INSERT_ID();
INSERT INTO submissions (uploaded_by, filename, shipper_name, sales_pic, shipper_status, potential_monthly_revenue, commodity_type, high_value_fragile, add_ons) VALUES ('workinpns@gmail.com', 'dummy_batch_5.csv', 'PT Jaya Makmur Retail', 'Siti Nurhaliza', 'new', 55000000, 'Textile', 1, NULL);
SET @sid_4 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kota Jakarta Timur', 'Kota Solo', 'CDD', 20026000.0, 19847100.0, 'Already bottom rate', 'Seryu', 18902000.0);
SET @rid_4_0 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_4_0, 'Kota Jakarta Timur', 'Kota Solo', 'CDD', 20026000.0, 19847100.0, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kota Jakarta Utara', 'Kab. Malang', 'Wingbox', NULL, 18999211.0, '', 'SJL', 17101000.0);
SET @rid_4_1 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kota Bandung', 'Kota Manado', 'Wingbox', NULL, 3662967.0, '', 'SJL', 3297000.0);
SET @rid_4_2 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kab. Bekasi', 'Kota Semarang', 'Wingbox', NULL, 12625404.0, '', 'Duta Trans', 11364000.0);
SET @rid_4_3 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kab. Bekasi', 'Kota Makassar', 'CDE', NULL, 3896277.0, '', 'AB Cargo', 3507000.0);
SET @rid_4_4 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kab. Tangerang', 'Kota Pekanbaru', 'CDD-L', NULL, 19689142.0, '', 'Duta Trans', 17722000.0);
SET @rid_4_5 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kota Jakarta Utara', 'Kab. Sidoarjo (Baru)', 'Wingbox', 10216000, NULL, 'No rate available', NULL, NULL);
SET @rid_4_6 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_4_6, 'Kota Jakarta Utara', 'Kab. Sidoarjo (Baru)', 'Wingbox', 10216000, NULL, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kota Bandung', 'Kota Manado', 'CDD', 14757000.0, 16109100.0, 'Already bottom rate', 'Seryu', 15342000.0);
SET @rid_4_7 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_4_7, 'Kota Bandung', 'Kota Manado', 'CDD', 14757000.0, 16109100.0, 'workinpns@gmail.com', 'resolved', 'AB Cargo', 13269000.0);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kab. Bekasi', 'Kab. Sidoarjo', 'CDD-L', NULL, 6602673.0, '', 'Duta Trans', 5943000.0);
SET @rid_4_8 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kota Jakarta Utara', 'Kab. Kediri', 'CDD-L', 6835000.0, 6975150.0, 'Already bottom rate', 'SJL', 6643000.0);
SET @rid_4_9 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_4_9, 'Kota Jakarta Utara', 'Kab. Kediri', 'CDD-L', 6835000.0, 6975150.0, 'workinpns@gmail.com', 'resolved', 'Duta Trans', 6229000.0);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kota Jakarta Timur', 'Kota Yogyakarta', 'CDD-L', 12054000.0, 13274100.0, 'Already bottom rate', 'SJL', 12642000.0);
SET @rid_4_10 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_4_10, 'Kota Jakarta Timur', 'Kota Yogyakarta', 'CDD-L', 12054000.0, 13274100.0, 'workinpns@gmail.com', 'resolved', 'Duta Trans', 10308000.0);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kota Jakarta Utara', 'Kota Yogyakarta (Baru)', 'CDD', 6113000, NULL, 'No rate available', NULL, NULL);
SET @rid_4_11 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_4_11, 'Kota Jakarta Utara', 'Kota Yogyakarta (Baru)', 'CDD', 6113000, NULL, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kota Jakarta Timur', 'Kota Makassar (Baru)', 'Wingbox', 13298000, NULL, 'No rate available', NULL, NULL);
SET @rid_4_12 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_4_12, 'Kota Jakarta Timur', 'Kota Makassar (Baru)', 'Wingbox', 13298000, NULL, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kota Jakarta Timur', 'Kota Yogyakarta', 'CDD', 4518000.0, 4356450.0, 'Already bottom rate', 'Duta Trans', 4149000.0);
SET @rid_4_13 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_4_13, 'Kota Jakarta Timur', 'Kota Yogyakarta', 'CDD', 4518000.0, 4356450.0, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kab. Tangerang', 'Kota Surabaya (Baru)', 'CDD-L', NULL, NULL, 'No rate available', NULL, NULL);
SET @rid_4_14 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_4_14, 'Kab. Tangerang', 'Kota Surabaya (Baru)', 'CDD-L', NULL, NULL, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kota Bandung', 'Kota Denpasar', 'Wingbox', NULL, 13625304.0, '', 'AB Cargo', 12264000.0);
SET @rid_4_15 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kota Jakarta Timur', 'Kota Palembang', 'Wingbox', 12354000.0, 13039950.0, 'Already bottom rate', 'Duta Trans', 12419000.0);
SET @rid_4_16 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_4_16, 'Kota Jakarta Timur', 'Kota Palembang', 'Wingbox', 12354000.0, 13039950.0, 'workinpns@gmail.com', 'in_progress', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kota Bandung', 'Kota Yogyakarta (Baru)', 'Wingbox', 4249000, NULL, 'No rate available', NULL, NULL);
SET @rid_4_17 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_4_17, 'Kota Bandung', 'Kota Yogyakarta (Baru)', 'Wingbox', 4249000, NULL, 'workinpns@gmail.com', 'open', NULL, NULL);
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kota Bandung', 'Kab. Banyuwangi', 'CDD', NULL, 5466120.0, '', 'Duta Trans', 4920000.0);
SET @rid_4_18 = LAST_INSERT_ID();
INSERT INTO submission_rows (submission_id, origin, destination, vehicle_type, target_rate, final_rate, remarks, matched_vendor, matched_cost) VALUES (@sid_4, 'Kota Bandung', 'Kota Cirebon (Baru)', 'CDE', 8452000, NULL, 'No rate available', NULL, NULL);
SET @rid_4_19 = LAST_INSERT_ID();
INSERT INTO vm_requests (submission_row_id, origin, destination, vehicle_type, target_rate, current_final_rate, requested_by, status, resolved_vendor, resolved_cost) VALUES (@rid_4_19, 'Kota Bandung', 'Kota Cirebon (Baru)', 'CDE', 8452000, NULL, 'workinpns@gmail.com', 'open', NULL, NULL);
